mode = "dark"

accent = "#c1121f"
selection = "#3f2024"
muted = "#5f6972"

background = "#151515"
dark_background = "#0f0f0f"
darker_background = "#080808"
lighter_background = "#242220"

foreground = "#efe5cf"
dark_foreground = "#8c877c"
light_foreground = "#d8ccb5"
bright_foreground = "#fff4dc"

red = "#c1121f"
yellow = "#d2a857"
orange = "#b76e2b"
green = "#76946a"
cyan = "#8fb7b0"
blue = "#6f8492"
magenta = "#a45a6a"
brown = "#7a5635"

bright_red = "#ef233c"
bright_yellow = "#f2c76e"
bright_green = "#9bbf87"
bright_cyan = "#b7d6cf"
bright_blue = "#9fb4c2"
bright_magenta = "#d08392"

hyprland_active_border = ["#c1121f", "#efe5cf"]
hyprland_inactive_border = "#4b4540aa"
